### PR TITLE
fix(vue3): Fix vue3 components remounting every time a key is added to state

### PR DESCRIPTION
**Pull request by alesgenova**

### CODE REVIEW

**Comment by alesgenova** [comment]
The codespell error is unrelated to this PR, it has to do with a typo in another commit message that ended up in the changelog

**Review by jourdain — CHANGES_REQUESTED** [review]
Can you trigger an event with `{type: "new-keys", keys: [...] }`. It won't be use right now, but could be useful down the road.

**Comment by alesgenova** [comment]
> Can you trigger an event with `{type: "new-keys", keys: [...] }`. It won't be use right now, but could be useful down the road.

Added the `new-keys` event, and actually refactored the fix to use it in `TrameTemplate.js`

**Review by jourdain — APPROVED** [review]

**Comment by jourdain** [comment]
Commit message should be `fix(vue3): prevent remounting when keys are added`

No upper case after `:`

**Comment by jourdain** [comment]
you can also edit the codespell check on the changelog

**Pull request merged**
